-- DROP SCHEMA numerical_twin;

CREATE SCHEMA numerical_twin AUTHORIZATION leakmited;

-- DROP TYPE numerical_twin."list_state_enum";

CREATE TYPE numerical_twin."list_state_enum" AS ENUM (
	'COMPUTED',
	'COMPUTING',
	'ERROR',
	'READY');

-- DROP TYPE numerical_twin."nt_cost_matrix_state_enum";

CREATE TYPE numerical_twin."nt_cost_matrix_state_enum" AS ENUM (
	'COMPUTED',
	'COMPUTING',
	'ERROR',
	'READY');

-- DROP TYPE numerical_twin."nt_data_product_job_run_status_enum";

CREATE TYPE numerical_twin."nt_data_product_job_run_status_enum" AS ENUM (
	'REGISTERED',
	'INITIATED',
	'IN_PROGRESS',
	'COMPLETED',
	'ERROR');

-- DROP TYPE numerical_twin."nt_data_product_job_run_trigger_enum";

CREATE TYPE numerical_twin."nt_data_product_job_run_trigger_enum" AS ENUM (
	'SCENARIO',
	'RENOVATION_METHOD',
	'COST_MATRIX',
	'RECOMPUTE_ALL',
	'RERUN');

-- DROP TYPE numerical_twin."nt_data_product_task_status_enum";

CREATE TYPE numerical_twin."nt_data_product_task_status_enum" AS ENUM (
	'REGISTERED',
	'INITIALIZED',
	'DATA_LOADED',
	'IN_PROGRESS',
	'COMPLETE',
	'ERROR');

-- DROP TYPE numerical_twin."nt_renovation_method_state_enum";

CREATE TYPE numerical_twin."nt_renovation_method_state_enum" AS ENUM (
	'COMPUTED',
	'COMPUTING',
	'ERROR',
	'READY');

-- DROP TYPE numerical_twin."nt_scenario_state_enum";

CREATE TYPE numerical_twin."nt_scenario_state_enum" AS ENUM (
	'COMPUTED',
	'COMPUTING',
	'ERROR',
	'READY');

-- DROP TYPE numerical_twin."pipe_material";

CREATE TYPE numerical_twin."pipe_material" AS ENUM (
	'BATO',
	'FONT',
	'PEHD',
	'PVCL');

-- DROP TYPE numerical_twin."plan_mode_enum";

CREATE TYPE numerical_twin."plan_mode_enum" AS ENUM (
	'edit',
	'validated',
	'locked',
	'live_view');

-- DROP SEQUENCE numerical_twin.nt_data_product_job_run_id_seq;

CREATE SEQUENCE numerical_twin.nt_data_product_job_run_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE numerical_twin.nt_data_product_job_run_status_id_seq;

CREATE SEQUENCE numerical_twin.nt_data_product_job_run_status_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE numerical_twin.nt_data_product_task_id_seq;

CREATE SEQUENCE numerical_twin.nt_data_product_task_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE numerical_twin.nt_data_product_task_status_id_seq;

CREATE SEQUENCE numerical_twin.nt_data_product_task_status_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE numerical_twin.numerical_twin_migration_table_id_seq;

CREATE SEQUENCE numerical_twin.numerical_twin_migration_table_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;-- numerical_twin.nt_data_product_task definition

-- Drop table

-- DROP TABLE numerical_twin.nt_data_product_task;

CREATE TABLE numerical_twin.nt_data_product_task (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	renovation_method_id uuid NOT NULL,
	cost_matrix_id uuid NOT NULL,
	scenario_id uuid NOT NULL,
	job_run_id int8 NOT NULL,
	databricks_task_id int8 NULL,
	created_at timestamptz DEFAULT now() NULL,
	updated_at timestamptz DEFAULT now() NULL,
	CONSTRAINT nt_data_product_task_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_nt_data_product_task_scenario_job_run ON numerical_twin.nt_data_product_task USING btree (scenario_id, job_run_id);


-- numerical_twin.nt_objective definition

-- Drop table

-- DROP TABLE numerical_twin.nt_objective;

CREATE TABLE numerical_twin.nt_objective (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar NOT NULL,
	description text NOT NULL,
	alpha numeric(2, 1) NOT NULL,
	CONSTRAINT nt_objective_alpha_check CHECK (((alpha >= (0)::numeric) AND (alpha <= (1)::numeric) AND (((alpha * (10)::numeric) % (1)::numeric) = (0)::numeric))),
	CONSTRAINT nt_objective_alpha_key UNIQUE (alpha),
	CONSTRAINT nt_objective_name_key UNIQUE (name),
	CONSTRAINT nt_objective_pkey PRIMARY KEY (id)
);


-- numerical_twin.numerical_twin_migration_table definition

-- Drop table

-- DROP TABLE numerical_twin.numerical_twin_migration_table;

CREATE TABLE numerical_twin.numerical_twin_migration_table (
	id serial4 NOT NULL,
	"timestamp" int8 NOT NULL,
	"name" varchar NOT NULL,
	CONSTRAINT "PK_4cf4739a4020421e6e5258c4ae2" PRIMARY KEY (id)
);


-- numerical_twin.nt_data_product_task_status definition

-- Drop table

-- DROP TABLE numerical_twin.nt_data_product_task_status;

CREATE TABLE numerical_twin.nt_data_product_task_status (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	task_id int8 NOT NULL,
	created_date timestamptz DEFAULT now() NULL,
	"status" numerical_twin."nt_data_product_task_status_enum" DEFAULT 'REGISTERED'::numerical_twin.nt_data_product_task_status_enum NOT NULL,
	CONSTRAINT nt_data_product_task_status_pkey PRIMARY KEY (id),
	CONSTRAINT fk_nt_data_product_task_status FOREIGN KEY (task_id) REFERENCES numerical_twin.nt_data_product_task(id) ON DELETE CASCADE
);
CREATE INDEX idx_nt_data_product_task_status_status ON numerical_twin.nt_data_product_task_status USING btree (status);
CREATE INDEX idx_nt_data_product_task_status_task_id ON numerical_twin.nt_data_product_task_status USING btree (task_id);
CREATE INDEX idx_nt_data_product_task_status_task_id_created_date ON numerical_twin.nt_data_product_task_status USING btree (task_id, created_date DESC);


-- numerical_twin."analyse" definition

-- Drop table

-- DROP TABLE numerical_twin."analyse";

CREATE TABLE numerical_twin."analyse" (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"type" varchar(50) NOT NULL,
	"date" timestamptz NOT NULL,
	"location" public.geometry(point, 4326) NOT NULL,
	measurements jsonb DEFAULT '[]'::jsonb NOT NULL,
	"status" varchar(50) NULL,
	organization_id int8 NOT NULL,
	created_by varchar(255) NOT NULL,
	created_date timestamptz DEFAULT now() NOT NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamptz DEFAULT now() NOT NULL,
	metadata jsonb NULL,
	CONSTRAINT analyse_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_analyse_date ON numerical_twin."analyse" USING btree (date);
CREATE INDEX idx_analyse_location ON numerical_twin."analyse" USING gist (location);
CREATE INDEX idx_analyse_organization ON numerical_twin."analyse" USING btree (organization_id);


-- numerical_twin.chantier_pipe_edition definition

-- Drop table

-- DROP TABLE numerical_twin.chantier_pipe_edition;

CREATE TABLE numerical_twin.chantier_pipe_edition (
	plan_chantier_id uuid NOT NULL,
	chantier_pipe_id varchar NOT NULL,
	chantier_pipe_geometries public.geometry(multilinestring, 4326) NULL,
	is_selected bool DEFAULT false NOT NULL,
	created_at timestamptz DEFAULT now() NOT NULL,
	arc_id varchar NULL,
	CONSTRAINT chantier_pipe_edition_pkey PRIMARY KEY (plan_chantier_id, chantier_pipe_id)
);
CREATE INDEX idx_chantier_pipe_edition_geometries ON numerical_twin.chantier_pipe_edition USING gist (chantier_pipe_geometries);
CREATE INDEX idx_chantier_pipe_edition_plan_chantier_id ON numerical_twin.chantier_pipe_edition USING btree (plan_chantier_id);


-- numerical_twin.list definition

-- Drop table

-- DROP TABLE numerical_twin.list;

CREATE TABLE numerical_twin.list (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar NOT NULL,
	organization_id int8 NOT NULL,
	created_by varchar(255) NOT NULL,
	created_date timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	budget int4 NULL,
	duration_in_years int4 NULL,
	start_year int4 DEFAULT EXTRACT(year FROM CURRENT_DATE) NULL,
	selected_alpha numeric(2, 1) NULL,
	cities _text NULL,
	lineage_metadata jsonb NULL,
	plan_mode numerical_twin."plan_mode_enum" DEFAULT 'edit'::numerical_twin.plan_mode_enum NOT NULL,
	state numerical_twin."list_state_enum" DEFAULT 'READY'::numerical_twin.list_state_enum NOT NULL,
	metadata_by_alpha jsonb NULL,
	renovation_method jsonb NULL,
	scenario jsonb NULL,
	CONSTRAINT "UQ_list_organization_id_name" UNIQUE (name, organization_id),
	CONSTRAINT nt_plan_pkey PRIMARY KEY (id),
	CONSTRAINT nt_plan_selected_alpha_check CHECK (((selected_alpha >= (0)::numeric) AND (selected_alpha <= (1)::numeric) AND ((selected_alpha * (10)::numeric) = floor((selected_alpha * (10)::numeric)))))
);


-- numerical_twin.list_chantier definition

-- Drop table

-- DROP TABLE numerical_twin.list_chantier;

CREATE TABLE numerical_twin.list_chantier (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	list_id uuid NOT NULL,
	"name" varchar NULL,
	"location" varchar NULL,
	expert_score float8 NULL,
	simplified_leakmited_risk varchar(1) NULL,
	matrix_cost float8 NOT NULL,
	detailed_geometry public.geometry(multilinestring, 4326) NULL,
	simplified_geometry public.geometry(point, 4326) NULL,
	vanne_id varchar(255) NULL,
	arc_ids _varchar NULL,
	"year" int4 DEFAULT EXTRACT(year FROM CURRENT_DATE) NULL,
	created_by varchar NULL,
	created_date timestamptz DEFAULT now() NULL,
	last_modified_by varchar NULL,
	last_modified_date timestamptz DEFAULT now() NULL,
	covered_length numeric(10, 2) DEFAULT 0 NOT NULL,
	expert_score_explanation jsonb DEFAULT '[]'::jsonb NOT NULL,
	non_normalized_expert_score float8 NULL,
	geometry_hash varchar(32) GENERATED ALWAYS AS (platformv2.geometry_hash(detailed_geometry)) STORED NULL,
	chantier_segments jsonb NULL,
	network_id int8 NULL,
	CONSTRAINT nt_plan_chantier_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_list_chantier_detailed_geometry ON numerical_twin.list_chantier USING gist (detailed_geometry);
CREATE INDEX idx_list_chantier_geometry_hash ON numerical_twin.list_chantier USING btree (geometry_hash) WHERE (geometry_hash IS NOT NULL);
CREATE INDEX idx_list_chantier_list_id ON numerical_twin.list_chantier USING btree (list_id);
CREATE INDEX idx_list_chantier_network_id ON numerical_twin.list_chantier USING btree (network_id);


-- numerical_twin.nt_cost_matrix definition

-- Drop table

-- DROP TABLE numerical_twin.nt_cost_matrix;

CREATE TABLE numerical_twin.nt_cost_matrix (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	organization_id int8 NOT NULL,
	"name" varchar NOT NULL,
	description varchar NULL,
	state numerical_twin."nt_cost_matrix_state_enum" DEFAULT 'READY'::numerical_twin.nt_cost_matrix_state_enum NULL,
	created_by varchar NOT NULL,
	created_date timestamptz DEFAULT now() NOT NULL,
	last_modified_by varchar NOT NULL,
	last_modified_date timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT nt_cost_matrix_organization_id_key UNIQUE (organization_id),
	CONSTRAINT nt_cost_matrix_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_nt_cost_matrix_organization_id ON numerical_twin.nt_cost_matrix USING btree (organization_id);


-- numerical_twin.nt_data_product_job_run definition

-- Drop table

-- DROP TABLE numerical_twin.nt_data_product_job_run;

CREATE TABLE numerical_twin.nt_data_product_job_run (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	databricks_job_run_id int8 NULL,
	"trigger" numerical_twin."nt_data_product_job_run_trigger_enum" NOT NULL,
	trigger_id text NOT NULL,
	organization_id int8 NOT NULL,
	created_date timestamptz DEFAULT now() NULL,
	last_modified_date timestamptz DEFAULT now() NULL,
	CONSTRAINT nt_data_product_job_run_pkey PRIMARY KEY (id),
	CONSTRAINT uq_databricks_job_run_id UNIQUE (databricks_job_run_id)
);
CREATE INDEX idx_nt_data_product_databricks_job_run_id ON numerical_twin.nt_data_product_job_run USING btree (databricks_job_run_id);
CREATE INDEX idx_nt_data_product_job_run_created_date ON numerical_twin.nt_data_product_job_run USING btree (created_date DESC);
CREATE INDEX idx_nt_data_product_job_run_organization_id ON numerical_twin.nt_data_product_job_run USING btree (organization_id);


-- numerical_twin.nt_data_product_job_run_status definition

-- Drop table

-- DROP TABLE numerical_twin.nt_data_product_job_run_status;

CREATE TABLE numerical_twin.nt_data_product_job_run_status (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	job_run_id int8 NOT NULL,
	created_date timestamptz DEFAULT now() NULL,
	"status" numerical_twin."nt_data_product_job_run_status_enum" DEFAULT 'REGISTERED'::numerical_twin.nt_data_product_job_run_status_enum NOT NULL,
	CONSTRAINT nt_data_product_job_run_status_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_nt_data_product_job_run_status_job_run_id ON numerical_twin.nt_data_product_job_run_status USING btree (job_run_id);


-- numerical_twin.nt_material_cost_matrix definition

-- Drop table

-- DROP TABLE numerical_twin.nt_material_cost_matrix;

CREATE TABLE numerical_twin.nt_material_cost_matrix (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	cost_matrix_id uuid NOT NULL,
	organization_id int8 NOT NULL,
	"name" varchar NOT NULL,
	description varchar NULL,
	material numerical_twin."pipe_material" NOT NULL,
	"table" jsonb NOT NULL,
	created_by varchar NOT NULL,
	created_date timestamptz DEFAULT now() NOT NULL,
	last_modified_by varchar NOT NULL,
	last_modified_date timestamptz DEFAULT now() NOT NULL,
	CONSTRAINT nt_material_cost_matrix_material_cost_matrix_id UNIQUE (material, cost_matrix_id),
	CONSTRAINT nt_material_cost_matrix_name_organization_id_key UNIQUE (name, organization_id),
	CONSTRAINT nt_material_cost_matrix_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_nt_material_cost_matrix_cost_matrix_id ON numerical_twin.nt_material_cost_matrix USING btree (cost_matrix_id);
CREATE INDEX idx_nt_material_cost_matrix_organization_id ON numerical_twin.nt_material_cost_matrix USING btree (organization_id);


-- numerical_twin.nt_org_config definition

-- Drop table

-- DROP TABLE numerical_twin.nt_org_config;

CREATE TABLE numerical_twin.nt_org_config (
	organization_id int8 NOT NULL,
	default_decision_sheet jsonb NULL,
	default_cost_matrix jsonb NULL,
	current_cost_matrix jsonb NULL,
	created_by varchar NULL,
	created_date timestamptz NULL,
	last_modified_by varchar NULL,
	last_modified_date timestamptz NULL,
	CONSTRAINT nt_org_config_pkey PRIMARY KEY (organization_id)
);


-- numerical_twin.nt_renovation_method definition

-- Drop table

-- DROP TABLE numerical_twin.nt_renovation_method;

CREATE TABLE numerical_twin.nt_renovation_method (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar NOT NULL,
	organization_id int8 NOT NULL,
	state numerical_twin."nt_renovation_method_state_enum" DEFAULT 'READY'::numerical_twin.nt_renovation_method_state_enum NOT NULL,
	rules jsonb DEFAULT '{"diameterRanges": []}'::jsonb NOT NULL,
	description text NULL,
	created_by varchar NULL,
	created_date timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	last_modified_by varchar NULL,
	last_modified_date timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	CONSTRAINT nt_renovation_method_organization_id_name_key UNIQUE (organization_id, name),
	CONSTRAINT nt_renovation_method_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_renovation_methods_organization_id ON numerical_twin.nt_renovation_method USING btree (organization_id);


-- numerical_twin.nt_scenario definition

-- Drop table

-- DROP TABLE numerical_twin.nt_scenario;

CREATE TABLE numerical_twin.nt_scenario (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar NOT NULL,
	description varchar NOT NULL,
	network_risk numeric DEFAULT 0 NULL,
	organization_id int8 NOT NULL,
	client_scenario bool DEFAULT true NOT NULL,
	decision_sheet jsonb NULL,
	expert_score_distribution jsonb NULL,
	state numerical_twin."nt_scenario_state_enum" DEFAULT 'READY'::numerical_twin.nt_scenario_state_enum NULL,
	created_by varchar(255) NOT NULL,
	created_date timestamptz DEFAULT now() NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamptz DEFAULT now() NULL,
	max_score_permillile jsonb NULL,
	CONSTRAINT nt_scenario_pkey PRIMARY KEY (id),
	CONSTRAINT uq_nt_scenario_name_organization_id UNIQUE (name, organization_id)
);


-- numerical_twin.plan definition

-- Drop table

-- DROP TABLE numerical_twin.plan;

CREATE TABLE numerical_twin.plan (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar NOT NULL,
	organization_id int8 NOT NULL,
	created_by varchar(255) NOT NULL,
	created_date timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	last_modified_by varchar(255) NOT NULL,
	last_modified_date timestamptz DEFAULT CURRENT_TIMESTAMP NULL,
	budget int4 NULL,
	duration_in_years int4 NULL,
	start_year int4 DEFAULT EXTRACT(year FROM CURRENT_DATE) NULL,
	CONSTRAINT "UQ_plan_name_organization_id" UNIQUE (name, organization_id),
	CONSTRAINT myip_pkey PRIMARY KEY (id)
);


-- numerical_twin.plan_chantier definition

-- Drop table

-- DROP TABLE numerical_twin.plan_chantier;

CREATE TABLE numerical_twin.plan_chantier (
	id uuid DEFAULT gen_random_uuid() NOT NULL,
	plan_id uuid NOT NULL,
	"name" varchar NULL,
	"location" varchar NULL,
	expert_score float8 NULL,
	non_normalized_expert_score float8 NULL,
	simplified_leakmited_risk varchar(1) NULL,
	matrix_cost float8 NOT NULL,
	"year" int4 NULL,
	detailed_geometry public.geometry(multilinestring, 4326) NULL,
	simplified_geometry public.geometry(point, 4326) NULL,
	vanne_id varchar(255) NULL,
	arc_ids _varchar NULL,
	covered_length numeric(10, 2) NOT NULL,
	expert_score_explanation jsonb DEFAULT '[]'::jsonb NOT NULL,
	source_type varchar(20) NOT NULL,
	created_by varchar(255) NULL,
	created_date timestamptz DEFAULT now() NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamptz DEFAULT now() NULL,
	origin_list_name varchar(255) NULL,
	geometry_hash varchar(32) GENERATED ALWAYS AS (platformv2.geometry_hash(detailed_geometry)) STORED NULL,
	renovation_method jsonb NULL,
	scenario jsonb NULL,
	location_image bytea NULL,
	chantier_image bytea NULL,
	material_distribution_image bytea NULL,
	diameter_distribution_image bytea NULL,
	installation_year_distribution_image bytea NULL,
	material_distribution_legend jsonb NULL,
	diameter_distribution_legend jsonb NULL,
	installation_year_distribution_legend jsonb NULL,
	new_material_distribution_image bytea NULL,
	new_material_distribution_legend jsonb NULL,
	chantier_segments jsonb NULL,
	network_id int8 NULL,
	CONSTRAINT planned_chantier_pkey PRIMARY KEY (id)
);
CREATE INDEX idx_plan_chantier_detailed_geometry ON numerical_twin.plan_chantier USING gist (detailed_geometry) WHERE (detailed_geometry IS NOT NULL);
CREATE INDEX idx_plan_chantier_geometry_hash ON numerical_twin.plan_chantier USING btree (geometry_hash) WHERE (geometry_hash IS NOT NULL);
CREATE INDEX idx_plan_chantier_network_id ON numerical_twin.plan_chantier USING btree (network_id);
CREATE INDEX idx_plan_chantier_plan_id ON numerical_twin.plan_chantier USING btree (plan_id);


-- numerical_twin.plan_chantier_user_defined_props definition

-- Drop table

-- DROP TABLE numerical_twin.plan_chantier_user_defined_props;

CREATE TABLE numerical_twin.plan_chantier_user_defined_props (
	plan_chantier_id uuid NOT NULL,
	"name" varchar NULL,
	address varchar NULL,
	renovation_method jsonb NULL,
	renovation_type varchar NULL,
	road_works_sync bool DEFAULT false NOT NULL,
	road_works_sync_comment text NULL,
	estimated_cost float8 NULL,
	validated bool DEFAULT false NOT NULL,
	"year" int4 NULL,
	saved_m3_per_year float8 NULL,
	efficiency_percent float8 NULL,
	created_by varchar(255) NULL,
	created_date timestamptz DEFAULT now() NOT NULL,
	last_modified_by varchar(255) NULL,
	last_modified_date timestamptz DEFAULT now() NOT NULL,
	detailed_geometry public.geometry(multilinestring, 4326) NULL,
	simplified_geometry public.geometry(point, 4326) NULL,
	arc_ids _varchar NULL,
	covered_length numeric(10, 2) NULL,
	chantier_segments jsonb NULL,
	matrix_cost float8 NULL,
	expert_score float8 NULL,
	non_normalized_expert_score float8 NULL,
	expert_score_explanation jsonb NULL,
	simplified_leakmited_risk varchar(1) NULL,
	network_id int8 NULL,
	CONSTRAINT plan_chantier_user_defined_props_pkey PRIMARY KEY (plan_chantier_id)
);
CREATE INDEX idx_plan_chantier_udp_geometry ON numerical_twin.plan_chantier_user_defined_props USING gist (detailed_geometry) WHERE (detailed_geometry IS NOT NULL);
CREATE INDEX idx_plan_chantier_udp_network_id ON numerical_twin.plan_chantier_user_defined_props USING btree (network_id);


-- numerical_twin."analyse" foreign keys

ALTER TABLE numerical_twin."analyse" ADD CONSTRAINT analyse_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id) ON DELETE CASCADE;


-- numerical_twin.chantier_pipe_edition foreign keys

ALTER TABLE numerical_twin.chantier_pipe_edition ADD CONSTRAINT fk_chantier_pipe_edition_plan_chantier FOREIGN KEY (plan_chantier_id) REFERENCES numerical_twin.plan_chantier(id) ON DELETE CASCADE;


-- numerical_twin.list foreign keys

ALTER TABLE numerical_twin.list ADD CONSTRAINT nt_plan_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id);


-- numerical_twin.list_chantier foreign keys

ALTER TABLE numerical_twin.list_chantier ADD CONSTRAINT nt_plan_chantier_plan_id_fkey FOREIGN KEY (list_id) REFERENCES numerical_twin.list(id) ON DELETE CASCADE;


-- numerical_twin.nt_cost_matrix foreign keys

ALTER TABLE numerical_twin.nt_cost_matrix ADD CONSTRAINT nt_cost_matrix_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id);


-- numerical_twin.nt_data_product_job_run foreign keys

ALTER TABLE numerical_twin.nt_data_product_job_run ADD CONSTRAINT fk_nt_data_product_job_run_organization_id FOREIGN KEY (organization_id) REFERENCES public.organization(id) ON DELETE CASCADE;


-- numerical_twin.nt_data_product_job_run_status foreign keys

ALTER TABLE numerical_twin.nt_data_product_job_run_status ADD CONSTRAINT fk_nt_data_product_job_run_status FOREIGN KEY (job_run_id) REFERENCES numerical_twin.nt_data_product_job_run(id) ON DELETE CASCADE;


-- numerical_twin.nt_material_cost_matrix foreign keys

ALTER TABLE numerical_twin.nt_material_cost_matrix ADD CONSTRAINT nt_material_cost_matrix_cost_matrix_id_fkey FOREIGN KEY (cost_matrix_id) REFERENCES numerical_twin.nt_cost_matrix(id) ON DELETE CASCADE;
ALTER TABLE numerical_twin.nt_material_cost_matrix ADD CONSTRAINT nt_material_cost_matrix_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id);


-- numerical_twin.nt_org_config foreign keys

ALTER TABLE numerical_twin.nt_org_config ADD CONSTRAINT nt_org_config_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id);


-- numerical_twin.nt_renovation_method foreign keys

ALTER TABLE numerical_twin.nt_renovation_method ADD CONSTRAINT nt_renovation_method_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id);


-- numerical_twin.nt_scenario foreign keys

ALTER TABLE numerical_twin.nt_scenario ADD CONSTRAINT nt_scenario_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id);


-- numerical_twin.plan foreign keys

ALTER TABLE numerical_twin.plan ADD CONSTRAINT myip_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organization(id) ON DELETE CASCADE;


-- numerical_twin.plan_chantier foreign keys

ALTER TABLE numerical_twin.plan_chantier ADD CONSTRAINT planned_chantier_myip_id_fkey FOREIGN KEY (plan_id) REFERENCES numerical_twin.plan(id) ON DELETE CASCADE;


-- numerical_twin.plan_chantier_user_defined_props foreign keys

ALTER TABLE numerical_twin.plan_chantier_user_defined_props ADD CONSTRAINT fk_plan_chantier_user_defined_props_plan_chantier FOREIGN KEY (plan_chantier_id) REFERENCES numerical_twin.plan_chantier(id) ON DELETE CASCADE;


-- numerical_twin.nt_data_product_job_run_with_current_status source

CREATE OR REPLACE VIEW numerical_twin.nt_data_product_job_run_with_current_status
AS SELECT jr.id,
    jr.databricks_job_run_id,
    jr.trigger,
    jr.trigger_id,
    jr.organization_id,
    jr.created_date,
    jr.last_modified_date,
    ls.status AS current_status,
    ls.created_date AS current_status_date,
    task_agg.tasks_status
   FROM numerical_twin.nt_data_product_job_run jr
     LEFT JOIN LATERAL ( SELECT s.status,
            s.created_date
           FROM numerical_twin.nt_data_product_job_run_status s
          WHERE s.job_run_id = jr.id
          ORDER BY s.created_date DESC
         LIMIT 1) ls ON true
     LEFT JOIN LATERAL ( SELECT
                CASE
                    WHEN bool_or(ts.status = 'ERROR'::numerical_twin.nt_data_product_task_status_enum) THEN 'ERROR'::text
                    WHEN bool_or(ts.status = 'IN_PROGRESS'::numerical_twin.nt_data_product_task_status_enum) THEN 'IN_PROGRESS'::text
                    WHEN bool_or(ts.status = 'COMPLETE'::numerical_twin.nt_data_product_task_status_enum) THEN 'COMPLETE'::text
                    ELSE 'REGISTERED'::text
                END AS tasks_status
           FROM numerical_twin.nt_data_product_task t
             LEFT JOIN LATERAL ( SELECT s.status
                   FROM numerical_twin.nt_data_product_task_status s
                  WHERE s.task_id = t.id
                  ORDER BY s.created_date DESC
                 LIMIT 1) ts ON true
          WHERE t.job_run_id = jr.id) task_agg ON true;


-- numerical_twin.nt_data_product_task_with_current_status source

CREATE OR REPLACE VIEW numerical_twin.nt_data_product_task_with_current_status
AS SELECT t.id,
    t.renovation_method_id,
    rm.name AS renovation_method_name,
    t.cost_matrix_id,
    t.scenario_id,
    sc.name AS scenario_name,
    t.job_run_id,
    jr.trigger AS job_run_trigger,
    t.databricks_task_id,
    t.created_at,
    t.updated_at,
    ls.status AS current_status,
    ls.created_date AS current_status_date
   FROM numerical_twin.nt_data_product_task t
     LEFT JOIN numerical_twin.nt_data_product_job_run jr ON jr.id = t.job_run_id
     LEFT JOIN numerical_twin.nt_renovation_method rm ON rm.id = t.renovation_method_id
     LEFT JOIN numerical_twin.nt_scenario sc ON sc.id = t.scenario_id
     LEFT JOIN LATERAL ( SELECT s.status,
            s.created_date
           FROM numerical_twin.nt_data_product_task_status s
          WHERE s.task_id = t.id
          ORDER BY s.created_date DESC
         LIMIT 1) ls ON true;


-- numerical_twin.nt_scenario_ready source

CREATE OR REPLACE VIEW numerical_twin.nt_scenario_ready
AS SELECT s.id,
        CASE
            WHEN NOT (EXISTS ( SELECT 1
               FROM numerical_twin.nt_data_product_task t
                 JOIN numerical_twin.nt_data_product_job_run jr ON t.job_run_id = jr.id
                 JOIN ( SELECT t_inner.scenario_id,
                        max(jr_inner.created_date) AS most_recent_job_date
                       FROM numerical_twin.nt_data_product_task t_inner
                         JOIN numerical_twin.nt_data_product_job_run jr_inner ON t_inner.job_run_id = jr_inner.id
                      WHERE t_inner.scenario_id = s.id
                      GROUP BY t_inner.scenario_id) recent_job ON t.scenario_id = recent_job.scenario_id AND jr.created_date = recent_job.most_recent_job_date
                 JOIN ( SELECT DISTINCT ON (nt_data_product_task_status.task_id) nt_data_product_task_status.task_id,
                        nt_data_product_task_status.status
                       FROM numerical_twin.nt_data_product_task_status
                      ORDER BY nt_data_product_task_status.task_id, nt_data_product_task_status.created_date DESC) latest_task_status ON t.id = latest_task_status.task_id
              WHERE t.scenario_id = s.id AND latest_task_status.status <> 'COMPLETE'::numerical_twin.nt_data_product_task_status_enum)) THEN true
            ELSE false
        END AS ready
   FROM numerical_twin.nt_scenario s;